import dotenv from "dotenv";
import mongoose from "mongoose";
import FoodCategory from "../models/foodCategory.js";
import FoodItem from "../models/food.js";
import Restaurant from "../models/restaurant.js";

dotenv.config({ path: ".env.development" });
dotenv.config();

const MONGODB_URI = process.env.MONGODB_CONNECTION_URI;

if (!MONGODB_URI) {
  console.error("Error: MONGODB_CONNECTION_URI environment variable is not defined.");
  process.exit(1);
}

const sampleCategories = [
  { CategoryName: "Biryani" },
  { CategoryName: "Burgers" },
  { CategoryName: "Pizza" },
  { CategoryName: "Chinese" },
  { CategoryName: "South Indian" },
  { CategoryName: "Desserts" },
  { CategoryName: "Beverages" },
  { CategoryName: "North Indian" },
  { CategoryName: "Japanese" },
  { CategoryName: "Mexican" },
];

const sampleRestaurantsData = [
  {
    name: "Royal Biryani House",
    ownerName: "Akbar Khan",
    description: "Authentic Hyderabadi and Dum Biryanis prepared with secret royal spices and premium basmati rice.",
    cuisine: ["Biryani", "North Indian", "Mughlai"],
    location: {
      address: "12/A Jubilee Hills Main Road",
      city: "Hyderabad",
      area: "Jubilee Hills",
      state: "Telangana",
      postalCode: "500033",
    },
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop",
    isVeg: false,
    priceRange: "₹400 for two",
    deliveryTime: "25-30 min",
    contact: {
      phone: "+91 9876543210",
      email: "contact@royalbiryani.com",
    },
    timing: { open: 11, close: 23 },
    foods: [
      {
        name: "Chicken Dum Biryani",
        description: "Marinated chicken layered with fragrant long-grain basmati rice, slow-cooked in traditional dum style.",
        price: 320,
        category: "Biryani",
        img_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: false,
        options: [
          {
            name: "Portion Size",
            type: "radio",
            values: [
              { label: "Half", price: 200 },
              { label: "Full", price: 320 },
              { label: "Jumbo Family Pack", price: 650 },
            ],
          },
        ],
      },
      {
        name: "Mutton Special Biryani",
        description: "Tender goat meat slow-cooked with saffron, spices, and ghee-infused basmati rice.",
        price: 450,
        category: "Biryani",
        img_url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: false,
        options: [],
      },
      {
        name: "Paneer Malai Tikka Biryani",
        description: "Grilled cottage cheese cubes in rich cream marinade layered with spiced aromatic rice.",
        price: 280,
        category: "Biryani",
        img_url: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?q=80&w=800&auto=format&fit=crop",
        rating: 4.6,
        is_veg: true,
        options: [],
      },
      {
        name: "Mirchi Ka Salan",
        description: "Traditional spicy green chili gravy with peanuts and sesame seeds.",
        price: 120,
        category: "North Indian",
        img_url: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?q=80&w=800&auto=format&fit=crop",
        rating: 4.5,
        is_veg: true,
        options: [],
      },
      {
        name: "Shahi Chicken Qorma",
        description: "Succulent chicken simmered in a creamy almond, cashew, and aromatic spice gravy.",
        price: 340,
        category: "North Indian",
        img_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=800&auto=format&fit=crop",
        rating: 4.7,
        is_veg: false,
        options: [],
      },
      {
        name: "Double Ka Meetha",
        description: "Hyderabadi royal bread pudding fried in ghee, soaked in saffron milk, topped with dry fruits.",
        price: 150,
        category: "Desserts",
        img_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: true,
        options: [],
      },
    ],
  },
  {
    name: "The Artisan Burger Co.",
    ownerName: "David Miller",
    description: "Gourmet hand-crafted smash burgers, crispy fries, and thick milkshakes made fresh daily.",
    cuisine: ["Burgers", "American", "Fast Food"],
    location: {
      address: "45 MG Road, Indiranagar",
      city: "Bengaluru",
      area: "Indiranagar",
      state: "Karnataka",
      postalCode: "560038",
    },
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop",
    isVeg: false,
    priceRange: "₹350 for two",
    deliveryTime: "20-25 min",
    contact: {
      phone: "+91 9123456789",
      email: "hello@artisanburger.co",
    },
    timing: { open: 12, close: 23 },
    foods: [
      {
        name: "Classic Cheese Smash Burger",
        description: "Double beef patty, double cheddar cheese, caramelized onions, and house secret sauce on brioche bun.",
        price: 260,
        category: "Burgers",
        img_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: false,
        options: [
          {
            name: "Cheese Add-on",
            type: "checkbox",
            values: [
              { label: "Extra Cheddar", price: 40 },
              { label: "Bacon Strips", price: 60 },
            ],
          },
        ],
      },
      {
        name: "Crispy Peri Peri Veggie Burger",
        description: "Crispy fried vegetable patty topped with peri-peri mayo, jalapenos, fresh lettuce, and tomatoes.",
        price: 190,
        category: "Burgers",
        img_url: "https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=800&auto=format&fit=crop",
        rating: 4.5,
        is_veg: true,
        options: [],
      },
      {
        name: "Smoky BBQ Bacon Burger",
        description: "Grilled juicy patty coated in rich hickory BBQ sauce, smoked bacon strips, crisp lettuce, and cheddar cheese.",
        price: 290,
        category: "Burgers",
        img_url: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: false,
        options: [],
      },
      {
        name: "Loaded Peri Peri Fries",
        description: "Golden crispy potato fries tossed in tangy spicy peri peri seasoning with cheese dip.",
        price: 140,
        category: "Burgers",
        img_url: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?q=80&w=800&auto=format&fit=crop",
        rating: 4.7,
        is_veg: true,
        options: [],
      },
      {
        name: "Crispy Golden Onion Rings & Aioli",
        description: "Thick-cut onion rings battered and fried to golden perfection, served with garlic aioli.",
        price: 150,
        category: "Burgers",
        img_url: "https://images.unsplash.com/photo-1639024471283-03518883512d?q=80&w=800&auto=format&fit=crop",
        rating: 4.6,
        is_veg: true,
        options: [],
      },
      {
        name: "Belgian Chocolate Milkshake",
        description: "Thick, creamy milkshake blended with dark Belgian chocolate and topped with whipped cream.",
        price: 180,
        category: "Beverages",
        img_url: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: true,
        options: [],
      },
    ],
  },
  {
    name: "Napoli Woodfired Pizza",
    ownerName: "Marco Rossi",
    description: "Authentic Neapolitan woodfired pizzas crafted with imported San Marzano tomatoes and mozzarella di bufala.",
    cuisine: ["Pizza", "Italian", "Pasta"],
    location: {
      address: "88 Bandra Kurla Complex",
      city: "Mumbai",
      area: "Bandra East",
      state: "Maharashtra",
      postalCode: "400051",
    },
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=800&auto=format&fit=crop",
    isVeg: true,
    priceRange: "₹500 for two",
    deliveryTime: "30-35 min",
    contact: {
      phone: "+91 9988776655",
      email: "orders@napolipizza.in",
    },
    timing: { open: 11, close: 22 },
    foods: [
      {
        name: "Classic Margherita Woodfired Pizza",
        description: "Fresh basil, extra virgin olive oil, Fior di Latte mozzarella, and San Marzano tomato sauce on 48h fermented crust.",
        price: 390,
        category: "Pizza",
        img_url: "https://images.unsplash.com/photo-1604382355076-af4b0eb60143?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: true,
        options: [
          {
            name: "Crust Size",
            type: "radio",
            values: [
              { label: "10 inch Medium", price: 390 },
              { label: "12 inch Large", price: 540 },
            ],
          },
        ],
      },
      {
        name: "Truffle Mushroom & Burrata Pizza",
        description: "Wild mushrooms, truffle cream, fresh burrata cheese, garlic, and fresh thyme.",
        price: 520,
        category: "Pizza",
        img_url: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: true,
        options: [],
      },
      {
        name: "Spicy Pepperoni Feast Pizza",
        description: "Loaded double pork pepperoni, spicy jalapenos, chili oil, mozzarella, and house tomato sauce.",
        price: 480,
        category: "Pizza",
        img_url: "https://images.unsplash.com/photo-1628840042765-356cda07504e?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: false,
        options: [],
      },
      {
        name: "Garlic Butter Stuffed Crust Sticks",
        description: "Freshly baked dough filled with mozzarella cheese, brushed with herbs and garlic butter.",
        price: 210,
        category: "Pizza",
        img_url: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?q=80&w=800&auto=format&fit=crop",
        rating: 4.7,
        is_veg: true,
        options: [],
      },
      {
        name: "Creamy Alfredo Fettuccine Pasta",
        description: "Ribbon fettuccine tossed in rich Parmesan butter cream sauce with sauteed garlic mushrooms.",
        price: 360,
        category: "Pizza",
        img_url: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?q=80&w=800&auto=format&fit=crop",
        rating: 4.7,
        is_veg: true,
        options: [],
      },
      {
        name: "Classic Italian Tiramisu",
        description: "Traditional espresso-soaked ladyfingers layered with creamy mascarpone cheese and cocoa powder.",
        price: 260,
        category: "Desserts",
        img_url: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: true,
        options: [],
      },
    ],
  },
  {
    name: "Golden Wok Chinese & Dim Sum",
    ownerName: "Lin Wei",
    description: "Delectable Asian cuisine featuring steamed dim sums, wok-tossed noodles, Schezwan fried rice, and Manchurian.",
    cuisine: ["Chinese", "Asian", "Thai"],
    location: {
      address: "14 Connaught Place",
      city: "New Delhi",
      area: "Connaught Place",
      state: "Delhi",
      postalCode: "110001",
    },
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?q=80&w=800&auto=format&fit=crop",
    isVeg: false,
    priceRange: "₹300 for two",
    deliveryTime: "25-30 min",
    contact: {
      phone: "+91 9811223344",
      email: "info@goldenwok.com",
    },
    timing: { open: 12, close: 23 },
    foods: [
      {
        name: "Schezwan Hakka Noodles",
        description: "Wok-tossed noodles with colorful bell peppers, spring onions, garlic, and spicy red chili Schezwan sauce.",
        price: 210,
        category: "Chinese",
        img_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?q=80&w=800&auto=format&fit=crop",
        rating: 4.7,
        is_veg: true,
        options: [],
      },
      {
        name: "Steamed Chicken Momos / Dim Sum",
        description: "Juicy minced chicken enclosed in delicate wrappers, served with fiery red chutney and broth.",
        price: 180,
        category: "Chinese",
        img_url: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: false,
        options: [],
      },
      {
        name: "Crispy Chili Paneer Dry",
        description: "Wok-tossed paneer cubes with green chilies, onions, garlic, and savory soy-sesame sauce.",
        price: 240,
        category: "Chinese",
        img_url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=800&auto=format&fit=crop",
        rating: 4.6,
        is_veg: true,
        options: [],
      },
      {
        name: "Triple Schezwan Chicken Fried Rice",
        description: "Combination of Schezwan chicken fried rice, soft noodles, and thick spicy Manchurian gravy with fried egg.",
        price: 290,
        category: "Chinese",
        img_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: false,
        options: [],
      },
      {
        name: "Hot & Sour Veg Manchow Soup",
        description: "Classic Indo-Chinese thick soup laden with finely chopped veggies, garlic, cilantro, topped with crispy fried noodles.",
        price: 140,
        category: "Chinese",
        img_url: "https://images.unsplash.com/photo-1547592180-85f173990554?q=80&w=800&auto=format&fit=crop",
        rating: 4.5,
        is_veg: true,
        options: [],
      },
      {
        name: "Honey Chili Crispy Potatoes",
        description: "Crispy potato fingers glazed in sweet honey, chili garlic paste, sesame seeds, and spring onions.",
        price: 190,
        category: "Chinese",
        img_url: "https://images.unsplash.com/photo-1518013431117-eb1465fa5752?q=80&w=800&auto=format&fit=crop",
        rating: 4.7,
        is_veg: true,
        options: [],
      },
    ],
  },
  {
    name: "Saravana Tiffin Centre",
    ownerName: "S. Ramanathan",
    description: "Traditional South Indian breakfast and meals served with fresh coconut chutneys, sambar, and filter coffee.",
    cuisine: ["South Indian", "Dosa", "Pure Veg"],
    location: {
      address: "72 T. Nagar Main Road",
      city: "Chennai",
      area: "T. Nagar",
      state: "Tamil Nadu",
      postalCode: "600017",
    },
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?q=80&w=800&auto=format&fit=crop",
    isVeg: true,
    priceRange: "₹150 for two",
    deliveryTime: "15-20 min",
    contact: {
      phone: "+91 9444112233",
      email: "saravana@tiffins.in",
    },
    timing: { open: 6, close: 22 },
    foods: [
      {
        name: "Ghee Roast Masala Dosa",
        description: "Crispy golden crepe roasted in pure desi ghee, stuffed with spiced potato mash, served with 3 chutneys and hot sambar.",
        price: 130,
        category: "South Indian",
        img_url: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: true,
        options: [],
      },
      {
        name: "Steamed Idli Sambar (4 pcs)",
        description: "Puffy soft steamed rice cakes soaked in aromatic piping-hot drumstick sambar and topped with ghee.",
        price: 90,
        category: "South Indian",
        img_url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: true,
        options: [],
      },
      {
        name: "Meda Vada (2 pcs)",
        description: "Crispy golden fried lentil donuts seasoned with peppercorns, ginger, and curry leaves.",
        price: 80,
        category: "South Indian",
        img_url: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?q=80&w=800&auto=format&fit=crop",
        rating: 4.7,
        is_veg: true,
        options: [],
      },
      {
        name: "Crispy Onion Rava Dosa",
        description: "Lacy, crunchy semolina dosa studded with chopped onions, green chilies, cumin seeds, roasted in ghee.",
        price: 140,
        category: "South Indian",
        img_url: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: true,
        options: [],
      },
      {
        name: "Authentic Kumbakonam Filter Coffee",
        description: "Piping hot chicory-infused strong South Indian dark roast coffee frothed with thick boiled milk.",
        price: 50,
        category: "Beverages",
        img_url: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: true,
        options: [],
      },
      {
        name: "Grand South Tiffin Thali Combo",
        description: "Platter containing 1 Mini Masala Dosa, 1 Idli, 1 Medu Vada, Rava Kesari sweet, sambar & chutneys.",
        price: 210,
        category: "South Indian",
        img_url: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: true,
        options: [],
      },
    ],
  },
  {
    name: "Sweet Dreams Bakery & Desserts",
    ownerName: "Chloe Dupont",
    description: "Heavenly artisanal cakes, warm waffles, molten lava cakes, and gourmet cheesecakes.",
    cuisine: ["Desserts", "Bakery", "Beverages"],
    location: {
      address: "102 Park Street",
      city: "Kolkata",
      area: "Park Street",
      state: "West Bengal",
      postalCode: "700016",
    },
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop",
    isVeg: true,
    priceRange: "₹250 for two",
    deliveryTime: "20-25 min",
    contact: {
      phone: "+91 9830011223",
      email: "chloe@sweetdreams.com",
    },
    timing: { open: 10, close: 23 },
    foods: [
      {
        name: "Warm Molten Choco Lava Cake",
        description: "Decadent dark chocolate cake with a warm flowing chocolate fudge center, served with vanilla ice cream.",
        price: 180,
        category: "Desserts",
        img_url: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: true,
        options: [],
      },
      {
        name: "New York Style Blueberry Cheesecake",
        description: "Rich, velvety baked cream cheese cake topped with tangy sweet wild blueberry compote.",
        price: 240,
        category: "Desserts",
        img_url: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: true,
        options: [],
      },
      {
        name: "Nutella Belgian Waffle",
        description: "Freshly baked crispy Belgian waffle smothered with warm Nutella spread and crushed hazelnut crumble.",
        price: 210,
        category: "Desserts",
        img_url: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: true,
        options: [],
      },
      {
        name: "Red Velvet Cream Cheese Cupcake",
        description: "Moist cocoa-infused red velvet sponge cake topped with swirl of silky cream cheese frosting.",
        price: 110,
        category: "Desserts",
        img_url: "https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?q=80&w=800&auto=format&fit=crop",
        rating: 4.7,
        is_veg: true,
        options: [],
      },
      {
        name: "Fudgy Chocolate Brownie Sundae",
        description: "Warm walnut fudge brownie served with two scoops of vanilla bean ice cream and hot fudge sauce.",
        price: 220,
        category: "Desserts",
        img_url: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: true,
        options: [],
      },
      {
        name: "Assorted French Macarons Box (4 pcs)",
        description: "Delicate French almond cookies filled with pistachio, raspberry, salted caramel, and dark chocolate ganache.",
        price: 280,
        category: "Desserts",
        img_url: "https://images.unsplash.com/photo-1569864358642-9d1684040f43?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: true,
        options: [],
      },
    ],
  },
  {
    name: "Boba & Brew Coffee Bar",
    ownerName: "Ethan Vance",
    description: "Specialty cold brews, iced matcha lattes, Taiwanese boba milk teas, and fresh breakfast toasts.",
    cuisine: ["Beverages", "American"],
    location: {
      address: "18 Koregaon Park Road 3",
      city: "Pune",
      area: "Koregaon Park",
      state: "Maharashtra",
      postalCode: "411001",
    },
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=800&auto=format&fit=crop",
    isVeg: true,
    priceRange: "₹300 for two",
    deliveryTime: "15-20 min",
    contact: {
      phone: "+91 9765432109",
      email: "sip@bobabrew.com",
    },
    timing: { open: 8, close: 22 },
    foods: [
      {
        name: "Taro Boba Milk Tea with Tapioca Pearls",
        description: "Creamy sweet taro root milk tea paired with chewy brown sugar tapioca boba pearls.",
        price: 220,
        category: "Beverages",
        img_url: "https://images.unsplash.com/photo-1558857563-b371033873b8?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: true,
        options: [],
      },
      {
        name: "Iced Caramel Macchiato",
        description: "Espresso combined with vanilla syrup, chilled milk, ice, and buttery caramel drizzle.",
        price: 210,
        category: "Beverages",
        img_url: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?q=80&w=800&auto=format&fit=crop",
        rating: 4.7,
        is_veg: true,
        options: [],
      },
      {
        name: "Smashed Avocado & Poached Egg Toast",
        description: "Artisanal sourdough slice topped with seasoned crushed avocado, cherry tomatoes, and microgreens.",
        price: 280,
        category: "Beverages",
        img_url: "https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800&auto=format&fit=crop",
        rating: 4.6,
        is_veg: false,
        options: [],
      },
      {
        name: "Brown Sugar Milk Tea with Cheese Foam",
        description: "Caramelized tiger stripe brown sugar syrup with fresh milk, boba, topped with salted cream cheese foam.",
        price: 240,
        category: "Beverages",
        img_url: "https://images.unsplash.com/photo-1558857563-b371033873b8?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: true,
        options: [],
      },
      {
        name: "Nitro Cold Brew Coffee",
        description: "16-hour slow steep Arabica cold brew infused with nitrogen for a silky smooth, naturally sweet head.",
        price: 190,
        category: "Beverages",
        img_url: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: true,
        options: [],
      },
      {
        name: "Blueberry Cream Cheese Toasted Bagel",
        description: "Warm toasted New York style bagel generously slathered with whipped blueberry cream cheese.",
        price: 170,
        category: "Beverages",
        img_url: "https://images.unsplash.com/photo-1585478259715-876acc5be8eb?q=80&w=800&auto=format&fit=crop",
        rating: 4.7,
        is_veg: true,
        options: [],
      },
    ],
  },
  {
    name: "Tandoori Nights Kebabs & Curries",
    ownerName: "Surjeet Singh",
    description: "Smokey char-grilled tandoori delicacies, succulent mutton galoutis, and buttery Mughlai curries.",
    cuisine: ["North Indian", "Mughlai"],
    location: {
      address: "56 Sector 18 Market",
      city: "Noida",
      area: "Sector 18",
      state: "Uttar Pradesh",
      postalCode: "201301",
    },
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=800&auto=format&fit=crop",
    isVeg: false,
    priceRange: "₹450 for two",
    deliveryTime: "30-35 min",
    contact: {
      phone: "+91 9810099887",
      email: "tandoori@nights.in",
    },
    timing: { open: 13, close: 23 },
    foods: [
      {
        name: "Chicken Tikka Kebab (6 pcs)",
        description: "Boneless chicken chunks marinated in spiced yogurt and mustard oil, roasted to perfection in clay oven.",
        price: 310,
        category: "North Indian",
        img_url: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: false,
        options: [],
      },
      {
        name: "Butter Chicken Special",
        description: "Charcoal roasted chicken tikka cooked in tomato cashew gravy finished with fenugreek and butter.",
        price: 360,
        category: "North Indian",
        img_url: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: false,
        options: [],
      },
      {
        name: "Mutton Galouti Kebab (4 pcs)",
        description: "Mouth-melting minced lamb patties infused with 32 royal aromatic spices, served with mint chutney.",
        price: 420,
        category: "North Indian",
        img_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: false,
        options: [],
      },
      {
        name: "Signature Dal Makhani",
        description: "Whole black lentils slow-cooked overnight with white butter, fresh cream, and subtle charcoal smoke.",
        price: 260,
        category: "North Indian",
        img_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: true,
        options: [],
      },
      {
        name: "Garlic Butter Naan (2 pcs)",
        description: "Soft refined flour flatbread stuffed with chopped garlic, baked in tandoor and brushed with butter.",
        price: 70,
        category: "North Indian",
        img_url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop",
        rating: 4.7,
        is_veg: true,
        options: [],
      },
      {
        name: "Gulab Jamun with Rabri (2 pcs)",
        description: "Warm fried milk dumplings soaked in cardamom sugar syrup, topped with chilled creamy rabri.",
        price: 140,
        category: "Desserts",
        img_url: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: true,
        options: [],
      },
    ],
  },
  {
    name: "Tokyo Sushi & Ramen Bar",
    ownerName: "Kenji Sato",
    description: "Authentic Japanese hand-rolled maki, fresh salmon nigiri, and rich slow-simmered ramen bowls.",
    cuisine: ["Japanese", "Asian"],
    location: {
      address: "22 Horizon Center, DLF Phase 5",
      city: "Gurugram",
      area: "DLF Phase 5",
      state: "Haryana",
      postalCode: "122002",
    },
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=800&auto=format&fit=crop",
    isVeg: false,
    priceRange: "₹650 for two",
    deliveryTime: "30-40 min",
    contact: {
      phone: "+91 9999887766",
      email: "sato@tokyoramen.com",
    },
    timing: { open: 12, close: 23 },
    foods: [
      {
        name: "Fresh Salmon Nigiri (4 pcs)",
        description: "Slices of fresh Atlantic salmon laid over vinegared sushi rice served with wasabi and pickled ginger.",
        price: 490,
        category: "Japanese",
        img_url: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: false,
        options: [],
      },
      {
        name: "Chicken Shoyu Tonkotsu Ramen",
        description: "Rich pork and chicken bone broth with wheat noodles, tender chashu chicken, soft-boiled egg, and nori.",
        price: 440,
        category: "Japanese",
        img_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: false,
        options: [],
      },
      {
        name: "Crunchy Spicy Tuna Roll (8 pcs)",
        description: "Raw yellowfin tuna rolled with cucumber, spicy sriracha mayo, rolled in crunchy tempura flakes.",
        price: 520,
        category: "Japanese",
        img_url: "https://images.unsplash.com/photo-1611143669185-af224c5e3252?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: false,
        options: [],
      },
      {
        name: "Vegetable Crispy Tempura Platter",
        description: "Battered and crispy fried seasonal vegetables served with sweet dashi soy dipping sauce.",
        price: 320,
        category: "Japanese",
        img_url: "https://images.unsplash.com/photo-1615361200141-f45040f367be?q=80&w=800&auto=format&fit=crop",
        rating: 4.6,
        is_veg: true,
        options: [],
      },
      {
        name: "Traditional Miso Soup",
        description: "Warm fermented soybean paste broth with silky tofu cubes, wakame seaweed, and scallions.",
        price: 160,
        category: "Japanese",
        img_url: "https://images.unsplash.com/photo-1547592180-85f173990554?q=80&w=800&auto=format&fit=crop",
        rating: 4.7,
        is_veg: true,
        options: [],
      },
      {
        name: "Matcha Green Tea Mochi Ice Cream (3 pcs)",
        description: "Sweet Japanese rice cake dough wrapped around premium green tea matcha ice cream center.",
        price: 240,
        category: "Desserts",
        img_url: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: true,
        options: [],
      },
    ],
  },
  {
    name: "Taco Fiesta Mexican Grill",
    ownerName: "Carlos Mendez",
    description: "Sizzling fajitas, loaded burritos, crunchy tacos, and fresh guacamole made with Hass avocados.",
    cuisine: ["Mexican", "Fast Food"],
    location: {
      address: "67 FC Road, Shivajinagar",
      city: "Pune",
      area: "Shivajinagar",
      state: "Maharashtra",
      postalCode: "411005",
    },
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=800&auto=format&fit=crop",
    isVeg: false,
    priceRange: "₹350 for two",
    deliveryTime: "25-30 min",
    contact: {
      phone: "+91 9112233445",
      email: "hola@tacofiesta.in",
    },
    timing: { open: 11, close: 22 },
    foods: [
      {
        name: "Loaded Grilled Chicken Nachos",
        description: "Crispy tortilla chips piled high with spiced chicken, melted queso cheese, black beans, jalapenos, and salsa.",
        price: 290,
        category: "Mexican",
        img_url: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?q=80&w=800&auto=format&fit=crop",
        rating: 4.7,
        is_veg: false,
        options: [],
      },
      {
        name: "Crispy Black Bean & Corn Tacos (3 pcs)",
        description: "Hard taco shells filled with seasoned black beans, sweet corn, shredded lettuce, pico de gallo, and sour cream.",
        price: 230,
        category: "Mexican",
        img_url: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=800&auto=format&fit=crop",
        rating: 4.6,
        is_veg: true,
        options: [],
      },
      {
        name: "Cheesy Chicken Quesadilla",
        description: "Grilled flour tortilla folded with shredded spiced chicken, blend of jack cheese, peppers, and chipotle mayo.",
        price: 280,
        category: "Mexican",
        img_url: "https://images.unsplash.com/photo-1618040996337-56904b7850b9?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: false,
        options: [],
      },
      {
        name: "Fiesta Chipotle Burrito Bowl",
        description: "Cilantro lime rice bowl topped with black beans, fajita veggies, guacamole, corn salsa, and fresh sour cream.",
        price: 310,
        category: "Mexican",
        img_url: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?q=80&w=800&auto=format&fit=crop",
        rating: 4.9,
        is_veg: true,
        options: [],
      },
      {
        name: "Cinnamon Sugar Churros with Chocolate Dip (4 pcs)",
        description: "Warm crispy Mexican fried dough pastries dusted in cinnamon sugar, served with warm chocolate fudge sauce.",
        price: 170,
        category: "Desserts",
        img_url: "https://images.unsplash.com/photo-1624371414361-e670edf4898d?q=80&w=800&auto=format&fit=crop",
        rating: 4.8,
        is_veg: true,
        options: [],
      },
      {
        name: "Fresh Mango Jalapeno Mocktail",
        description: "Refreshing cooler made with fresh Alphonso mango puree, lime juice, sparkling soda, and a touch of spicy jalapeno.",
        price: 150,
        category: "Beverages",
        img_url: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=800&auto=format&fit=crop",
        rating: 4.7,
        is_veg: true,
        options: [],
      },
    ],
  },
];

async function seedDatabase() {
  try {
    console.log("Connecting to MongoDB...");
    await mongoose.connect(MONGODB_URI as string);
    console.log("Connected successfully!");

    console.log("Clearing existing sample data (Restaurants, FoodItems, FoodCategories)...");
    await Restaurant.deleteMany({});
    await FoodItem.deleteMany({});
    await FoodCategory.deleteMany({});

    console.log("Seeding Food Categories...");
    const createdCategories = await FoodCategory.insertMany(sampleCategories);
    console.log(`Inserted ${createdCategories.length} Categories.`);

    console.log("Seeding Restaurants & Food Items...");
    let totalFoodItems = 0;

    for (const restData of sampleRestaurantsData) {
      const { foods, ...restaurantFields } = restData;

      // Create Restaurant document first
      const restaurantDoc = new Restaurant({
        ...restaurantFields,
        menu: [],
      });
      await restaurantDoc.save();

      // Create Food Items linked to this restaurant
      const foodDocs = [];
      for (const food of foods) {
        const foodDoc = new FoodItem({
          ...food,
          restaurantId: restaurantDoc._id,
          restaurntName: restaurantDoc.name,
        });
        await foodDoc.save();
        foodDocs.push(foodDoc._id);
        totalFoodItems++;
      }

      // Update restaurant's menu with food ObjectIds
      restaurantDoc.menu = foodDocs as any;
      await restaurantDoc.save();
      console.log(` -> Created Restaurant "${restaurantDoc.name}" with ${foodDocs.length} items.`);
    }

    console.log(`\n🎉 Seed completed successfully! Created ${sampleRestaurantsData.length} restaurants and ${totalFoodItems} food items.`);
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }
}

seedDatabase();
