import { useCookie } from "./useCookie";

/**
 * @description Hook to manage user for authentication
 * @returns {addUser, removeUser} Functions to manage in Redux
 */
export const useUser = () => {
  const { setItem, removeItem } = useCookie();

  /**
   * @description Sets the auth token to cookie
   * @param token AuthToken generated by JWT 
   */
  const addUser = (token: string | undefined | null) => {
    if (!token) {
      throw new Error("addUser : token is empty");
    }
    setItem("authToken", token);
  };

  const removeUser = () => {
    removeItem("authToken");
  };
  return { addUser, removeUser };
};
